FROM php:7.0-apache 

MAINTAINER Adam Zouari <adam.zouari@heig-vd.ch>
MAINTAINER Oussama Lagha <oussama.lagha@heig-vd.ch>
RUN apt-get update && \
apt-get install -y nano


COPY content/ /var/www/html/
 

